# Generated by Django 2.1.5 on 2019-01-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190131_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_name',
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
