# Generated by Django 2.0.10 on 2019-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_photo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
